In [75]:
#Import Libraries 
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np

In [20]:
iris = load_iris()

In [24]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [25]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [26]:
iris.data_module

'sklearn.datasets.data'

In [29]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['species'] = iris.target
df['species'] = df['species'].apply(lambda x: iris.target_names[x])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [63]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size = 0.2)

In [64]:
from sklearn import svm

In [65]:
model = svm.SVC(kernel='rbf', C = 30, gamma ='auto')
model.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [66]:
model.score(X_test,y_test)

0.9666666666666667

In [70]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel = 'linear', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [71]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [74]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 150, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([1.        , 0.96666667, 0.9       , 0.93333333, 1.        ])

In [81]:
kernals = ['rbf', 'linear']
C = [1,10,20]
avg_score = {}
for kvals in kernals:
    for cvals in C:
        cv_score = cross_val_score(svm.SVC(kernel = kvals, C = cvals, gamma = 'auto'), iris.data, iris.target, cv = 5)
        avg_score[kvals + '_' + str(cvals)] = np.average(cv_score)

avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

GridsearchCV

In [94]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma= 'auto'), {
    'C' : [1,10,20],
    'kernel' : ['rbf', 'linear']
}, cv = 5, return_train_score = False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00220537, 0.00059996, 0.00080032, 0.00080132, 0.00099864,
        0.00103164]),
 'std_fit_time': array([9.81997858e-04, 4.89862464e-04, 7.48697804e-04, 4.00666405e-04,
        5.70931608e-06, 2.71160652e-05]),
 'mean_score_time': array([0.00100393, 0.00059996, 0.00059991, 0.00039983, 0.00039845,
        0.00023746]),
 'std_score_time': array([0.00063249, 0.00048986, 0.00048982, 0.00048969, 0.000488  ,
        0.00040008]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6])}

In [95]:
results =pd.DataFrame(clf.cv_results_)

In [96]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002205,0.000982,0.001004,0.000632,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000600,0.000490,0.000600,0.000490,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000800,0.000749,0.000600,0.000490,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000801,0.000401,0.000400,0.000490,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000999,0.000006,0.000398,0.000488,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001032,0.000027,0.000237,0.000400,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6

In [99]:
results[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [100]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']

In [101]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [103]:
clf.best_score_

0.9800000000000001

In [113]:
from sklearn.model_selection import RandomizedSearchCV
clf_r = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    'C' : [1,10,20],
    'kernel' : ['rgb', 'linear']
},cv =5, return_train_score = False)

clf_r.fit(iris.data, iris.target)
clf_r.cv_results_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:292: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py", line 315, in _dense_fit
    ) = libsvm.fit(
  File "sklearn\svm\_libsvm.pyx", line 173, in sklearn.svm._libsvm.fit
ValueError: 'rgb' is not in list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [       nan 0.98              nan 0.97333333        nan 0.96666667]
  warnings.warn(

{'mean_fit_time': array([0.00161843, 0.00099564, 0.00099277, 0.00099807, 0.00060077,
        0.00059419]),
 'std_fit_time': array([4.70067304e-04, 9.38654885e-06, 6.21607213e-04, 6.30451496e-04,
        4.90656223e-04, 4.85286840e-04]),
 'mean_score_time': array([0.        , 0.00061245, 0.        , 0.00040679, 0.        ,
        0.0006052 ]),
 'std_score_time': array([0.        , 0.00050047, 0.        , 0.00049837, 0.        ,
        0.00049439]),
 'param_kernel': masked_array(data=['rgb', 'linear', 'rgb', 'linear', 'rgb', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rgb', 'C': 1},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'rgb', 'C': 10},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'rgb', 'C': 20},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([       nan, 0.96666667,        nan, 1.        ,        nan,
        1.        ]),
 'split1_test_score': array([nan,  1., nan,  1., nan,  1.]),
 'split2_test_score': array([       nan, 0.96666667,        nan, 0.9       ,        nan,
        0.9       ]),
 'split3_test_score': array([       nan, 0.96666667,        nan, 0.96666667,        nan,
        0.93333333]),
 'split4_test_score': array([nan,  1., nan,  1., nan,  1.]),
 'mean_test_score': array([       nan, 0.98      ,        nan, 0.97333333,        nan,
        0.96666667]),
 'std_test_score': array([       nan, 0.01632993,        nan, 0.03887301,        nan,
        0.0421637 ]),
 'rank_test_score': array([4, 1, 5, 2, 6, 3])}

In [114]:
df_r =pd.DataFrame(clf_r.cv_results_)
df_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001618,0.000470,0.000000,0.000000,rgb,1,"{'kernel': 'rgb', 'C': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
1,0.000996,0.000009,0.000612,0.000500,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000993,0.000622,0.000000,0.000000,rgb,10,"{'kernel': 'rgb', 'C': 10}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.000998,0.000630,0.000407,0.000498,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
4,0.000601,0.000491,0.000000,0.000000,rgb,20,"{'kernel': 'rgb', 'C': 20}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
5,0.000594,0.000485,0.000605,0.000494,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3

In [115]:
df_r[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rgb              NaN
1       1       linear         0.980000
2      10          rgb              NaN
3      10       linear         0.973333
4      20          rgb              NaN
5      20       linear         0.966667